mysite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.shortcuts import redirect
from django.urls import include, path

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda request: redirect('polls/', permanent=False)),
    path('polls/', include('polls.urls')),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.QuestionView.as_view(), name='question'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('users/', views.UserListView.as_view(), name='user_list'),
    path('users/<int:pk>', views.UserView.as_view(), name='user'),
    path('<int:pk>/add_comment/', views.CreateCommentView.as_view(), name='add_comment'),
]

polls/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def is_hidden(self):
        return self.pub_date > timezone.now() or not self.choice_set.exists()

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    class Meta:
        ordering = ['-votes']

    def __str__(self):
        return self.choice_text


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=100, default='Please add a profile')

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_and_save_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


class Comment(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text

polls/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['question', 'created_date', 'author', 'text']

    def __init__(self, question_pk=None, username=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs['autofocus'] = True

        if question_pk:
            self.fields['question'].initial = question_pk
            self.fields['question'].disabled = True
        if username:
            self.fields['author'].initial = username
        self.fields['created_date'].disabled = True

polls/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views.generic import CreateView, DetailView, ListView

from .forms import CommentForm
from .models import Choice, Question


class IndexView(ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class QuestionView(DetailView):
    model = Question
    template_name = 'polls/question.html'

    def get_object(self, queryset=None):
        question = super().get_object(queryset)
        if question.is_hidden() and not self.request.user.is_superuser:
            raise Http404('No question found matching the query')
        return question


class ResultsView(DetailView):
    model = Question
    template_name = 'polls/results.html'

    def get_object(self, queryset=None):
        question = super().get_object(queryset)
        if question.is_hidden() and not self.request.user.is_superuser:
            raise Http404('No question found matching the query')
        return question


@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request, 'polls/question.html', {'question': question, 'error_message': "You didn't select a choice."}
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=[question.id]))


class UserListView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'polls/user_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['staff'] = [user for user in User.objects.all() if user.is_staff]
        context['non_staff'] = [user for user in User.objects.all() if not user.is_staff]
        return context


class UserView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'polls/user.html'


class CreateCommentView(CreateView):
    form_class = CommentForm
    template_name = 'polls/add_comment.html'

    def get_success_url(self):
        return reverse('polls:question', kwargs={'pk': self.object.question.id})

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['question_pk'] = self.kwargs.get('pk')
        kwargs['username'] = self.request.user.username
        return kwargs

polls/templates/polls/add_comment.html
{% extends 'polls/base.html' %}

{% load crispy_forms_tags %}

{% block body %}

<div class="row">
  <div class="col-md-6">
    <h1 class="mt-2">New Comment</h1>
    <hr class="mt-0 mb-4">

    <form method="post" class="post-form">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-success">Send</button>
    </form>
  </div>
</div>

{% endblock body %}

polls/templates/polls/base.html
{% load static %}
<!doctype html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %} Polls {% endblock %}</title>
  <link rel="stylesheet" href="https://bootswatch.com/4/cosmo/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
  {% block stylesheets %}
  {% endblock %}
</head>

<body>
  {% include 'polls/navbar.html' %}

  <div class="container">
    {% block body %}
    {% endblock %}
  </div>

  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
  {% block javascripts %}
  {% endblock %}
</body>

</html>

polls/templates/polls/detail.html
{% include 'registration/login_bar.html' %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %}
  {% for choice in question.choice_set.all %}
  <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
  <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
  {% endfor %}
  <input type="submit" value="Vote">
</form>

<a href="{% url 'polls:add_comment' question.id %}">Add comment</a>

{% for comment in question.comment_set.all %}
<p>{{ comment.created_date}} by {{ comment.author }}</p>
<p>{{ comment.text|linebreaks }}</p>
{% empty %}
<p>No comments here yet :(</p>
{% endfor %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block body %}

<div class="row">
  <div class="col-md-6">
    {% if latest_question_list %}
    <ul>
      {% for question in latest_question_list %}
      <li><a href="{% url 'polls:question' question.id %}">{{ question.question_text }}</a> (<a
          href="{% url 'polls:results' question.id %}" class="text-success">results</a>)</li>
      {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
  </div>
</div>

{% endblock body %}

polls/templates/polls/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-primary mb-3">
  <div class="container">
    <a href="{% url 'polls:index' %}" class="navbar-brand">Polls</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mobile-nav">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="mobile-nav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a href="/" class="nav-link text-light">home</a>
        </li>

        <li class="nav-item">
          <a href="{% url 'polls:user_list' %}" class="nav-link text-light">users</a>
        </li>

        {% if user.is_staff %}
        <li class="nav-item">
          <a href="{% url 'admin:index' %}" class="nav-link text-light">admin</a>
        </li>
        {% endif %}

        <li class="nav-item">
          {% if user.is_authenticated %}
          <b><a href="{% url 'logout' %}" class="nav-link text-light">logout</a></b>
          {% else %}
          <b><a href="{% url 'login' %}" class="nav-link text-light">login</a></b>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>

polls/templates/polls/question.html
{% extends 'polls/base.html' %}

{% block body %}

<div class="row">
  <div class="col-md-6">
    <h1 class="mt-2">{{ question.question_text }}</h1>
    <hr class="mt-0 mb-4">

    {% if error_message %}
    <div class="alert alert-danger">{{ error_message }}</div>
    {% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
      {% csrf_token %}
      {% for choice in question.choice_set.all %}
      <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
      <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
      <br>
      {% endfor %}
      <input type="submit" value="Vote" role="button" class="btn btn-success my-2">
    </form>

    <a href="{% url 'polls:add_comment' question.id %}">Add comment</a>
  </div>
</div>

<div class="row">
  <div class="col-6">
    {% for comment in question.comment_set.all %}
    <hr>
    <p>{{ comment.created_date}} by <i>{{ comment.author }}</i></p>
    <p>{{ comment.text|linebreaks }}</p>
    {% empty %}
    <hr>
    <p>No comments here yet :(</p>
    {% endfor %}
  </div>
</div>

{% endblock body %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block body %}

<div class="row">
  <div class="col-md-6">
    <h1 class="mt-2">{{ question.question_text }}</h1>
    <hr class="mt-0 mb-4">

    <table class="table table-striped table-sm table-hover">
      <tr>
        <th>Language</th>
        <th>Votes</th>
      </tr>
      {% for choice in question.choice_set.all %}
      {% if forloop.first  %}
      <tr class="table-success">
        <td>{{ choice.choice_text }}</td>
        <td>{{ choice.votes }}</td>
      </tr>
      {% else %}
      <tr>
        <td>{{ choice.choice_text }}</td>
        <td>{{ choice.votes }}</td>
      </tr>
      {% endif %}
      {% endfor %}
    </table>

    <a href="{% url 'polls:question' question.id %}">Vote again?</a>
  </div>
</div>

{% endblock body %}

polls/templates/polls/user.html
{% extends 'polls/base.html' %}

{% block body %}

<div class="row">
  <div class="col-md-6">
    <ul>
      <li>username: {{ user.username }}</li>
      <li>status:
        {% if user.is_staff %}
        staff
        {% else %}
        non-staff
        {% endif %}
      </li>
      <li>bio: {{ user.profile.bio }}</li>
    </ul>
  </div>
</div>

{% endblock body %}

polls/templates/polls/user_list.html
{% extends 'polls/base.html' %}

{% block body %}

<div class="row">
  <div class="col-md-6">
    <h2>Staff</h2>
    
    {% if staff %}
    <ul>
      {% for user in staff %}
      <li><a href="{% url 'polls:user' user.id %}">{{ user.username }}</a> (Bio: {{ user.profile.bio }})</li>
      {% endfor %}
    </ul>
    {% else %}
    <p>No staffers are available.</p>
    {% endif %}
    <hr>
    
    <h2>Non-Staff</h2>
    
    {% if non_staff %}
    <ul>
      {% for user in non_staff %}
      <li><a href="{% url 'polls:user' user.id %}">{{ user.username }}</a> (Bio: {{ user.profile.bio }})</li>
      {% endfor %}
    </ul>
    {% else %}
    <p>No non-staffers are available.</p>
    {% endif %}
    <hr>
    
    <h3>Everybody!</h3>
    
    {% if user_list %}
    <ul>
      {% for user in user_list %}
      <li><a href="{% url 'polls:user' user.id %}">{{ user.username }}</a> (Bio: {{ user.profile.bio }})</li>
      {% endfor %}
    </ul>
    {% else %}
    <p>No users are available.</p>
    {% endif %}
  </div>
</div>

{% endblock body %}

polls/templates/polls/users.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% include 'registration/login_bar.html' %}

<h2>Staff</h2>

{% if staff %}
<ul>
  {% for user in staff %}
  <li>{{ user.profile }} (Bio: {{ user.profile.bio }})</li>
  {% endfor %}
</ul>
{% else %}
<p>No staffers are available.</p>
{% endif %}

<h2>Non-Staff</h2>

{% if non_staff %}
<ul>
  {% for user in non_staff %}
  <li>{{ user.profile }} (Bio: {{ user.profile.bio }})</li>
  {% endfor %}
</ul>
{% else %}
<p>No non-staffers are available.</p>
{% endif %}

<h3>Everybody!</h3>

{% if user_list %}
<ul>
  {% for user in user_list %}
  <li>{{ user.profile }} (Bio: {{ user.profile.bio }})</li>
  {% endfor %}
</ul>
{% else %}
<p>No users are available.</p>
{% endif %}